### ISSUE TITLE
The Road to Type Classes

### ISSUE THREAD

**Issue by magnus-madsen** [flix/flix#1000]
This ticket is to track the long road towards type classes. It will involve at least the following steps:

- Ensuring well-kinded types.
- Adding contexts to the Typer.
- Adding support for built-in Eq and Ord classes.
- Adding proper monomorph support.
- Adding type classes to the frontend of the compiler.
- Adding support for arbitrary type classes to the Typer.
- Adding support for user-defined instances.
- Adding a language for automatically deriving instances.

**Comment by timjs** [comment]
What are your thoughts on nominal vs structural type classes? As in: will Flix type classes be nominal like traits/protocols in [Rust](https://doc.rust-lang.org/book/ch10-02-traits.html), [Scala](https://docs.scala-lang.org/tour/traits.html), [Swift](https://docs.swift.org/swift-book/LanguageGuide/Protocols.html) and [Pony](https://tutorial.ponylang.io/types/traits-and-interfaces.html)? Or will they be structural like interfaces in [Golang](https://gobyexample.com/interfaces) and [Pony](https://tutorial.ponylang.io/types/traits-and-interfaces.html) interfaces?

Nominal type classes have the property that instances can be automatically selected. However, they require [coherence rules](https://doc.rust-lang.org/reference/items/implementations.html#trait-implementation-coherence) and have problems with [orphans](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/separate_compilation.html#orphan-modules). ([blog post 1](http://blog.ezyang.com/2014/07/type-classes-confluence-coherence-global-uniqueness/), [blog post 2](http://pchiusano.github.io/2018-02-13/typeclasses.html))

Structural type classes are more flexible, but types can [accidentally](https://github.com/golang/go/issues/34996) implement an interface and behave in an unexpected way.

**Comment by magnus-madsen** [comment]
I was definitely thinking along the lines of nominal with a nice system for type class instance derivation. 

What are the major strengths of structural type classes? I am not sure how such a design even looks!

**Comment by magnus-madsen** [comment]
We do have important structural types in Flix: tuples and extensible records

**Comment by timjs** [comment]
> What are the major strengths of structural type classes? I am not sure how such a design even looks!

The only languages I know of that have this feature is Pony (which has both traits and interfaces) and Golang (which has only interfaces). I'm really not sure what the impact of accidentally confirming to a structural interface is on a big code base in, e.g., Golang...

> I was definitely thinking along the lines of nominal with a nice system for type class instance derivation.

I think that, at the moment, this is the most researched and tested approach. Difficulty lies in having a type from package A and a trait from package B and you'd like to have a trait implementation in package C, which is an [_orphan_](https://wiki.haskell.org/Orphan_instance).

Haskell, PureScript, Rust, and Swift all have this problem. It is not easy solved. Therefore, I was thinking about structural interfaces a la Golang. But as I already stated, I'm not aware of the impact on big code bases...

**Comment by magnus-madsen** [comment]
> I think that, at the moment, this is the most researched and tested approach. Difficulty lies in having a type from package A and a trait from package B and you'd like to have a trait implementation in package C, which is an [_orphan_](https://wiki.haskell.org/Orphan_instance).

I think this is solved by whole-program compilation. (But of course- that has its own downsides and is possibly something we may want to move away from).

An alternative is to "explicitly import" the instance derivation rules you are interested. In an abstract sence, Scala already supports this because you can use imports to control what implicits are brought into scope. But in Scala it feels very ad-hoc. It would be interesting to look into a more principled mechanism.

**Comment by timjs** [comment]
You’ll still have the orphan problem with whole program compilation. It’s about _the library_ where the instance/implementation is defined.

Same example: lib A defines a type, lib defines a type class. Say we’d allow orphans, which are defined in lib C _and_ lib D. Than we’ll have a problem when using all those libs together!

Maybe a solution would be to allow orphans only in _application code_, but not in library code. But I’ll have to think about that.

**Comment by SethTisue** [comment]
curious which of the todo items here are now done and which still remain

**Comment by magnus-madsen** [comment]
We are 95% done. We have a few sharp edges left, e.g. how to deal with extensible records, but for most uses type classes are ready for use. For example, we already have `Eq`, `Order`, and `Foldable`. That's the short answer at least :)

**Comment by magnus-madsen** [comment]
For some examples of what already works:

https://github.com/flix/flix/blob/master/main/src/library/Eq.flix
https://github.com/flix/flix/blob/master/main/src/library/Foldable.flix

We are mostly focused on the rounding the sharp edges and extending the standard library.

We are also rebuilding the "flixdoc" from the ground to support type classes and their instances.

**Comment by magnus-madsen** [comment]
We now have type classes (and have had for a while!)
