### ISSUE TITLE
Use functional style in `Packager`

### ISSUE THREAD

**Issue by mlutze** [flix/flix#3132]
The `Packager` currently relies on throwing and catching exceptions. We should change this to use `Result`/`Validation`s to line up with our style guide.

**Comment by magnus-madsen** [comment]
Fixed in master.

**Comment by mlutze** [comment]
Not fixed yet! We still have some `RuntimeException`s mucking about.

**Comment by KengoTODA** [comment]
And +1 more TODO here:

https://github.com/flix/flix/blob/e4afa9135dac6fe50185a055a0892c813c64d337/main/src/ca/uwaterloo/flix/tools/Packager.scala#L383
