### ISSUE TITLE
Classic `Fix`

### ISSUE THREAD

**Issue by xgrommx** [flix/flix#4689]
Hello, how can I write classic `Fix` in flix?

I mean `newtype Fix f = Fix (f (Fix f))`, I try
```
enum Fix[f] {
    case In (f(Fix[f]))
}
```
But it doesn't work.

**Comment by JonathanStarup** [comment]
I'm not familiar with this Fix example, do you have a reference? I'm not sure if it it's right but I gave it a go
```
enum Fix[f: Type -> Type] {
    case Fix(f[Fix[f]])
}
```

**Comment by xgrommx** [comment]
@JonathanStarup I tried it, but it doesn't work 
https://play.flix.dev/?q=KYOwrgtgBAYglgDwNoDMBcUAqBPADsKAWgD4s9gBdKAbwCgoGoBjAQwGcD4EAKFJL1BQoBKWgF8gA

**Comment by JonathanStarup** [comment]
hmm yes that's curious. It works on master. I can't think of any changes related to this. Do you have some input @mlutze?

**Comment by mlutze** [comment]
I believe it is because higher-order types don't play nicely with enums. This ticket mentions the same issue: https://github.com/flix/flix/issues/2113

**Comment by xgrommx** [comment]
@JonathanStarup I can build from master and it will be works?

**Comment by JonathanStarup** [comment]
Yeah it works for me. I believe a new flix version will also come in the next couple days so you can also wait for that if you'd prefer

**Comment by magnus-madsen** [comment]
flix.dev/nightly

**Comment by magnus-madsen** [comment]
Resolved?

**Comment by JonathanStarup** [comment]
I was mistaken, I though it worked on master because I thought it was a compiletime error, but its a runtime error. It's still broken

**Comment by mlutze** [comment]
Fixed by enum monomorphization.
