### ISSUE TITLE
"run" broken on tests within a namespace in VSCode

### ISSUE THREAD

**Issue by paulbutcher** [flix/flix#4716]
This may be a regression (I seem to recall this working before, but can't be sure). Clicking on "run" below:

<img width="522" alt="Screenshot 2022-10-16 at 11 20 56" src="https://user-images.githubusercontent.com/61163/196030071-b4cd5416-4082-4fb9-b545-a91eada2714b.png">

Results in:

```
flix> :eval JavaUtils.testFindMatches()
-- Resolution Error -------------------------------------------------- <shell>  

>> Definition 'JavaUtils.testFindMatches' is not accessible from the namespace '/'.

2 | println(JavaUtils.testFindMatches()) as \ IO
            ^^^^^^^^^^^^^^^^^^^^^^^^^
            inaccessible definition.

Tip: Mark the definition as public.
```

**Comment by JonathanStarup** [comment]
I think it's been like this for some time, the entry point has to be public but vscode doesn't check

**Comment by magnus-madsen** [comment]
Proposal:

- Hide "Run" for non-public functions.

(The alternative is way too cumbersome).

**Comment by paulbutcher** [comment]
> * Hide "Run" for non-public functions.

This works for me.

**Comment by magnus-madsen** [comment]
I think this has been fixed (?)

**Comment by paulbutcher** [comment]
> I think this has been fixed (?)

I don't think so: or at least I'm still seeing it with a freshly built `flix.jar`? Which change were you expecting would have fixed this?

**Comment by magnus-madsen** [comment]
I guess the change was only in my mind then :)

**Comment by magnus-madsen** [comment]
A one line change somewhere in CodeLensProvider.
